name: cicd

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'

jobs:

  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/metadata-action@v4
        id: metadata
        with:
          images: runmymind/steamcmd
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: int128/kaniko-action@v1
        with:
          push: true
          file: ./docker/Dockerfile
          context: ./docker
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          kaniko-args: |
            --use-new-run 
            --cleanup 
            --compressed-caching=false
